#### Path ####
BASE_PATH: "../Datasets/BCI_Competition_IV/BCI_Competition_IV_2a"
LOG_PATH: "./logs"
CKPT_PATH: "./checkpoints"

#### Setting step ####
SEED: 45
GPU_NUM: "0"
num_workers: 0

#### Training step ####
EPOCHS: 1000
batch_size: 64
lr: 2e-3

weight_decay: 0.075
k_folds: 5

#### Experiment variable ####
task: "BCICompet2a"
num_classes: 4
num_channels: 22
downsampling: 0

num_subjects: 9
sampling_rate: 250
target_subject: 0
is_test: False

#### Etc ###
log_etc: "Baseline"
momentum: 0.9
